In [1]:
from pandas import Series, DataFrame

In [2]:
import pandas as pd

In [6]:
df1 = DataFrame({'key':['b','b','a','c','a','a','b'],
                 'data1':range(7)})

In [8]:
df2 = DataFrame({'key':['a','b','d'],
                 'data2' : range(3)})

In [10]:
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b

In [11]:
df2

data2 key
0      0   a
1      1   b
2      2   d

In [12]:
pd.merge(df1,df2)

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [14]:
pd.merge(df1,df2,on='key')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [17]:
df3 = DataFrame({'lkey':['b','b','a','c','a','a','b'],
                 'data1': range(7)})

In [18]:
df4 = DataFrame({'rkey':['a','b','d'],
                 'data2':range(3)})

In [19]:
pd.merge(df3,df4,left_on='lkey', right_on='rkey')

data1 lkey  data2 rkey
0      0    b      1    b
1      1    b      1    b
2      6    b      1    b
3      2    a      0    a
4      4    a      0    a
5      5    a      0    a

In [20]:
pd.merge(df1,df2, how='outer')

data1 key  data2
0    0.0   b    1.0
1    1.0   b    1.0
2    6.0   b    1.0
3    2.0   a    0.0
4    4.0   a    0.0
5    5.0   a    0.0
6    3.0   c    NaN
7    NaN   d    2.0

In [21]:
df1 = DataFrame({'key':['b','b','a','c','a','b'],
                 'data1': range(6)})

In [22]:
df2 = DataFrame({'key': ['a','b','a','b','d'],
                 'data2': range(5)})

In [23]:
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   b

In [24]:
df2

data2 key
0      0   a
1      1   b
2      2   a
3      3   b
4      4   d

In [25]:
pd.merge(df1,df2, on='key', how='left')

data1 key  data2
0       0   b    1.0
1       0   b    3.0
2       1   b    1.0
3       1   b    3.0
4       2   a    0.0
5       2   a    2.0
6       3   c    NaN
7       4   a    0.0
8       4   a    2.0
9       5   b    1.0
10      5   b    3.0

In [27]:
pd.merge(df1,df2, on='key', how='inner')

data1 key  data2
0      0   b      1
1      0   b      3
2      1   b      1
3      1   b      3
4      5   b      1
5      5   b      3
6      2   a      0
7      2   a      2
8      4   a      0
9      4   a      2

In [28]:
left = DataFrame({'key1':['foo','foo','bar'],
                  'key2': ['one','two','one'],
                  'lval': [1,2,3]})

In [29]:
right = DataFrame({'key1': ['foo','foo','bar','bar'],
                   'key2': ['one','one','one','two'],
                   'rval': [4,5,6,7]})

In [30]:
pd.merge(left,right, on=['key1','key2'], how='outer')

key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0

In [31]:
pd.merge(left, right, on='key1')

key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [32]:
pd.merge(left,right, on='key1', suffixes=('_left','_right'))

key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

# Merging on Index 

In [33]:
left1 = DataFrame({'key':['a','b','a','a','b','c'],
                   'value': range(6)})

In [35]:
right1 = DataFrame({'group_val':[3.5,7]},
                    index=['a','b'])

In [36]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [37]:
right1

group_val
a        3.5
b        7.0

In [38]:
pd.merge(left1,right1, left_on='key', right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [39]:
pd.merge(left1,right1,left_on='key', right_index=True, how='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [41]:
import numpy as np

In [42]:
lefth = DataFrame({'key1':['Ohio','Ohio','Ohio','Nevada','Nevada'],
                   'key2':[2000,2001,2002,2001,2002],
                   'data':np.arange(5.)})

In [43]:
righth = DataFrame(np.arange(12).reshape((6,2)),
                   index=[['Nevada','Nevada','Ohio','Ohio','Ohio','Ohio']],
                   columns=['event1','event2'])

In [44]:
righth

event1  event2
Nevada       0       1
Nevada       2       3
Ohio         4       5
Ohio         6       7
Ohio         8       9
Ohio        10      11

In [45]:
lefth

data    key1  key2
0   0.0    Ohio  2000
1   1.0    Ohio  2001
2   2.0    Ohio  2002
3   3.0  Nevada  2001
4   4.0  Nevada  2002

In [48]:
pd.merge(lefth,righth,left_on=['key1','key2'], right_index=True)

ValueError: len(left_on) must equal the number of levels in the index of "right"

In [49]:
left2 = DataFrame([[1.,2.],[3.,4.],[5.,6.]], index=['a','c','e'],
                  columns=['Ohio','Nevada'])

In [50]:
right2 = DataFrame([[7.,8.],[9.,10.],[11.,12.],[13.,14.]],
                   index=['b','c','d','e'], columns=['Missouri','Alabama'])

In [51]:
left2

Ohio  Nevada
a   1.0     2.0
c   3.0     4.0
e   5.0     6.0

In [52]:
right2

Missouri  Alabama
b       7.0      8.0
c       9.0     10.0
d      11.0     12.0
e      13.0     14.0

In [53]:
pd.merge(left2, right2, how='outer', left_index=True, right_index=True)

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [54]:
left2.join(right2, how='outer')

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [55]:
left1.join(right1, on='key')

key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

In [56]:
another = DataFrame([[7.,8.],[9.,10.],[11.,12.],[16.,17.]],
                    index=['a','c','e','f'], columns=['New York', 'Oregon'])

In [58]:
left2.join([right2, another])

Ohio  Nevada  Missouri  Alabama  New York  Oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
c   3.0     4.0       9.0     10.0       9.0    10.0
e   5.0     6.0      13.0     14.0      11.0    12.0

In [59]:
left2.join([right2, another], how='outer')

Ohio  Nevada  Missouri  Alabama  New York  Oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
b   NaN     NaN       7.0      8.0       NaN     NaN
c   3.0     4.0       9.0     10.0       9.0    10.0
d   NaN     NaN      11.0     12.0       NaN     NaN
e   5.0     6.0      13.0     14.0      11.0    12.0
f   NaN     NaN       NaN      NaN      16.0    17.0

# Concatening Along an Axis

In [60]:
arr = np.arange(12).reshape((3,4))

In [61]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
np.concatenate([arr,arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [63]:
s1 = Series([0,1], index=['a','b'])

In [64]:
s2 = Series([2,3,4], index=['c','d','e'])

In [65]:
s3 = Series([5,6], index=['f','g'])

In [66]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [67]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [68]:
pd.concat([s1,s2,s3], axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [70]:
s4 = pd.concat([s1  * 5, s3])

In [71]:
pd.concat([s1,s4],axis=1)

0  1
a  0.0  0
b  1.0  5
f  NaN  5
g  NaN  6

In [72]:
pd.concat([s1,s4],axis=1,join='inner')

0  1
a  0  0
b  1  5

In [73]:
pd.concat([s1,s4], axis=1, join_axes=[['a','c','b','e']])

0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  5.0
e  NaN  NaN

In [74]:
result = pd.concat([s1,s1,s3], keys=['one','two','three'])

In [75]:
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [76]:
result.unstack()

a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0

In [77]:
pd.concat([s1,s2,s3], axis=1,keys=['one','two','three'])

one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [78]:
df1 = DataFrame(np.arange(6).reshape(3,2), index=['a','b','c'],
                columns=['one','two'])

In [79]:
df2 = DataFrame(5 + np.arange(4).reshape(2,2), index=['a','c'],
                columns=['three','four'])

In [80]:
pd.concat([df1,df2], axis=1, keys=['level1','level2'])

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [81]:
pd.concat({'level1': df1, 'level2':df2}, axis=1)

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [82]:
pd.concat([df1, df2], axis=1, keys=['level1','level2'],
          names=['upper','lower'])

upper level1     level2     
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [83]:
df1 = DataFrame(np.random.randn(3,4), columns=['a','b','c','d'])

In [84]:
df2 = DataFrame(np.random.randn(2,3), columns=['b','d','a'])

In [85]:
df1

a         b         c         d
0  0.214566  0.904914  1.813322  0.625872
1 -0.593470 -1.023406  0.902370 -0.474649
2  0.977795  0.035642 -1.098902  0.852460

In [86]:
df2

b         d         a
0  0.524903 -0.311041 -1.797267
1 -1.925800 -1.636451 -1.756409

In [87]:
pd.concat([df1,df2], ignore_index=True)

a         b         c         d
0  0.214566  0.904914  1.813322  0.625872
1 -0.593470 -1.023406  0.902370 -0.474649
2  0.977795  0.035642 -1.098902  0.852460
3 -1.797267  0.524903       NaN -0.311041
4 -1.756409 -1.925800       NaN -1.636451

# Reshaping and Pivoting

In [90]:
data = DataFrame(np.arange(6).reshape((2,3)),
                index=pd.Index(['Ohio','Colorado'], name='state'),
                columns=pd.Index(['one','two','three'], name='number'))

In [91]:
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [92]:
result = data.stack()

In [93]:
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [94]:
result.unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [95]:
result.unstack(0)

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [96]:
result.unstack('state')

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [97]:
s1 = Series([0,1,2,3], index=['a','b','c','d'])

In [98]:
s2 = Series([4,5,6], index=['c','d','e'])

In [99]:
data2 = pd.concat([s1,s2], keys=['one','two'])

In [100]:
data2.unstack()

a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

In [101]:
data2.unstack().stack()

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
two  c    4.0
     d    5.0
     e    6.0
dtype: float64

In [102]:
data2.unstack().stack(dropna=False)

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
     e    NaN
two  a    NaN
     b    NaN
     c    4.0
     d    5.0
     e    6.0
dtype: float64

In [104]:
df = DataFrame({'left': result, 'right': result + 5},
                columns=pd.Index(['left','right'], name='side'))

In [105]:
df

side             left  right
state    number             
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10

In [106]:
df.unstack('state')

side   left          right         
state  Ohio Colorado  Ohio Colorado
number                             
one       0        3     5        8
two       1        4     6        9
three     2        5     7       10

In [107]:
df.unstack('state').stack('side')

state         Ohio  Colorado
number side                 
one    left      0         3
       right     5         8
two    left      1         4
       right     6         9
three  left      2         5
       right     7        10

# Data Transformation

# Removing Duplicates

In [109]:
data = DataFrame({'k1':['one'] * 3 + ['two'] * 4,
                 'k2': [1,1,2,3,3,4,4]})

In [110]:
data

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [111]:
data.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [112]:
data.drop_duplicates()

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [113]:
data['v1'] = range(7)

In [114]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
3  two   3   3

In [115]:
data.drop_duplicates(['k1','k2'], take_last=True)

C:\Users\Tapan Chovatia\GraphLab\Anaconda2\envs\gl-env\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: the take_last=True keyword is deprecated, use keep='last' instead
  if __name__ == '__main__':


k1  k2  v1
1  one   1   1
2  one   2   2
4  two   3   4
6  two   4   6

In [116]:
data = DataFrame({'food':['bacon','pulled pork','bacon','Pastrami','corned beef', 'Bacon', 'pastrami','honey ham','nova lox'],
                  'ounces':[4,3,12,6,7.5,8,3,5,6]})

In [117]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [118]:
meat_to_animal= {
    'bacon':'pig',
    'pulled pork':'pig',
    'pastrami':'cow',
    'corned beef':'cow',
    'honey ham':'pig',
    'nova lox':'salmon'
}

In [119]:
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)

In [120]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [121]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

# Replacing Values

In [122]:
data = Series([1.,-999.,2.,-999., -1000., 3.])

In [123]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [124]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [125]:
data.replace([-999, -1000], [np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [126]:
data.replace({-999:np.nan, -1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

# Renaming Axis Indexes

In [127]:
data = DataFrame(np.arange(12).reshape((3,4)),
                 index=['Ohio','Colorado','New York'],
                 columns=['one','two','three','four'])

In [128]:
data.index.map(str.upper)

array(['OHIO', 'COLORADO', 'NEW YORK'], dtype=object)

In [129]:
data.index = data.index.map(str.upper)

In [130]:
data

one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [131]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [133]:
data.rename(index={'OHIO':'INDIANA'},
           columns={'three':'peekaboo'})

one  two  peekaboo  four
INDIANA     0    1         2     3
COLORADO    4    5         6     7
NEW YORK    8    9        10    11

In [134]:
_=data.rename(index={'OHIO':'INDIANA'}, inplace=True)

In [135]:
data

one  two  three  four
INDIANA     0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

# Descritization and binning

In [136]:
ages = [20,22,25,27,21,23,37,31,61,45,41,32]

In [137]:
bins = [18,25,35,60,100]

In [138]:
cats = pd.cut(ages,bins)

In [139]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, object): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [140]:
cats.labels

C:\Users\Tapan Chovatia\GraphLab\Anaconda2\envs\gl-env\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: 'labels' is deprecated. Use 'codes' instead
  if __name__ == '__main__':


array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [141]:
cats.levels

C:\Users\Tapan Chovatia\GraphLab\Anaconda2\envs\gl-env\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: Accessing 'levels' is deprecated, use 'categories'
  if __name__ == '__main__':


Index([u'(18, 25]', u'(25, 35]', u'(35, 60]', u'(60, 100]'], dtype='object')

In [142]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [143]:
pd.cut(ages,[18,26,36,61,100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, object): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [144]:
group_names = ['Youth','YouthAdult','MiddleAged','Senior']

In [145]:
pd.cut(ages,bins,labels=group_names)

[Youth, Youth, Youth, YouthAdult, Youth, ..., YouthAdult, Senior, MiddleAged, MiddleAged, YouthAdult]
Length: 12
Categories (4, object): [Youth < YouthAdult < MiddleAged < Senior]

In [146]:
data = np.random.randn(20)

In [147]:
pd.cut(data,4, precision=2)

[(-2.56, -1.35], (1.05, 2.25], (-1.35, -0.15], (-1.35, -0.15], (-0.15, 1.05], ..., (-0.15, 1.05], (-0.15, 1.05], (-0.15, 1.05], (-2.56, -1.35], (-1.35, -0.15]]
Length: 20
Categories (4, object): [(-2.56, -1.35] < (-1.35, -0.15] < (-0.15, 1.05] < (1.05, 2.25]]

In [148]:
data = np.random.randn(1000)

In [149]:
cats = pd.qcut(data,4)

In [150]:
cats

[(-0.0903, 0.572], (-0.0903, 0.572], [-2.882, -0.785], [-2.882, -0.785], (-0.785, -0.0903], ..., (-0.0903, 0.572], (-0.785, -0.0903], (-0.785, -0.0903], (-0.0903, 0.572], (-0.0903, 0.572]]
Length: 1000
Categories (4, object): [[-2.882, -0.785] < (-0.785, -0.0903] < (-0.0903, 0.572] < (0.572, 3.214]]

In [151]:
pd.value_counts(cats)

(0.572, 3.214]       250
(-0.0903, 0.572]     250
(-0.785, -0.0903]    250
[-2.882, -0.785]     250
dtype: int64

In [152]:
pd.qcut(data, [0,0.1,0.5,0.9,1.])

[(-0.0903, 1.181], (-0.0903, 1.181], [-2.882, -1.411], [-2.882, -1.411], (-1.411, -0.0903], ..., (-0.0903, 1.181], (-1.411, -0.0903], (-1.411, -0.0903], (-0.0903, 1.181], (-0.0903, 1.181]]
Length: 1000
Categories (4, object): [[-2.882, -1.411] < (-1.411, -0.0903] < (-0.0903, 1.181] < (1.181, 3.214]]

# Detecting and Filtering Outliers

In [153]:
np.random.seed(12345)

In [154]:
data = DataFrame(np.random.randn(1000,4))

In [155]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

In [156]:
col = data[3]

In [157]:
col[np.abs(col)>3]

97     3.927528
305   -3.399312
400   -3.745356
Name: 3, dtype: float64

In [158]:
data[(np.abs(data)>3).any(1)]

0         1         2         3
5   -0.539741  0.476985  3.248944 -1.021228
97  -0.774363  0.552936  0.106061  3.927528
102 -0.655054 -0.565230  3.176873  0.959533
305 -2.315555  0.457246 -0.025907 -3.399312
324  0.050188  1.951312  3.260383  0.963301
400  0.146326  0.508391 -0.196713 -3.745356
499 -0.293333 -0.242459 -3.056990  1.918403
523 -3.428254 -0.296336 -0.439938 -0.867165
586  0.275144  1.179227 -3.184377  1.369891
808 -0.362528 -3.548824  1.553205 -2.186301
900  3.366626 -2.372214  0.851010  1.332846

In [159]:
data[np.abs(data) > 3] = np.sign(data) * 3

In [160]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067623     0.068473     0.025153    -0.002081
std       0.995485     0.990253     1.003977     0.989736
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.000000     2.653656     3.000000     3.000000

In [161]:
df = DataFrame(np.arange(5*4).reshape(5,4))

In [162]:
sampler = np.random.permutation(5)

In [163]:
sampler

array([1, 0, 2, 3, 4])

In [164]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [165]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [166]:
df.take(np.random.permutation(len(df))[:3])

0   1   2   3
1   4   5   6   7
3  12  13  14  15
4  16  17  18  19

In [167]:
bag = np.array([5,7,-1,6,4])

In [168]:
sampler = np.random.randint(0, len(bag), size=10)

In [169]:
sampler

array([4, 4, 2, 2, 2, 0, 3, 0, 4, 1])

In [170]:
draws = bag.take(sampler)

In [171]:
draws

array([ 4,  4, -1, -1, -1,  5,  6,  5,  4,  7])

# Computing indicator/dummy variables

In [172]:
df = DataFrame({'key':['b','b','a','c','a','b'],
                'data1': range(6)})

In [173]:
df

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   b

In [174]:
pd.get_dummies(df['key'])

a    b    c
0  0.0  1.0  0.0
1  0.0  1.0  0.0
2  1.0  0.0  0.0
3  0.0  0.0  1.0
4  1.0  0.0  0.0
5  0.0  1.0  0.0

In [175]:
dummies = pd.get_dummies(df['key'],prefix='key')

In [177]:
df_with_dummy = df[['data1']].join(dummies)

In [178]:
df_with_dummy

data1  key_a  key_b  key_c
0      0    0.0    1.0    0.0
1      1    0.0    1.0    0.0
2      2    1.0    0.0    0.0
3      3    0.0    0.0    1.0
4      4    1.0    0.0    0.0
5      5    0.0    1.0    0.0

In [179]:
mnames = ['movie_id', 'title', 'genres']

# Check further in book